const FETCH_RECIPE_START="FETCH_RECIPE_START";
const FETCH_RECIPE_SUCCESS="FETCH_RECIPE_SUCCESS";
const FETCH_RECIPE_FAILED="FETCH_RECIPE_FAILED";

export {FETCH_RECIPE_START,FETCH_RECIPE_SUCCESS,FETCH_RECIPE_FAILED}